version: "3"
services:
  api:
    build: .
    # depends_on:
    #   postgres
    ports:
      # - <port on localhost>:<port on container>
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi

#     volumes:
#       postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres


